language: julia

os:
  - linux

julia:
  - 0.7
  - 1.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

sudo: false

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
